import {
  UserProfile,
  Vehicle,
  Hotspot,
  Ride,
  GhostPrediction,
  Pod,
  Wallet,
  ModeratorCase,
  AuditLogEntry,
} from '../types';

export const CHENNAI_CENTER = {
  lat: 13.0827,
  lng: 80.2707,
};

// 10 safe Chennai pickup hotspots
export const SEED_HOTSPOTS: Hotspot[] = [
  {
    id: 'hs-1',
    name: 'Guindy Metro Station',
    category: 'metro',
    lat: 13.0092,
    lng: 80.2131,
    lit: true,
    legalStopping: true,
    waitingCount: 3,
    historicalConfidence: 94,
    avgWaitMins: 4,
  },
  {
    id: 'hs-2',
    name: 'Adyar Signal',
    category: 'junction',
    lat: 13.0063,
    lng: 80.2575,
    lit: true,
    legalStopping: true,
    waitingCount: 2,
    historicalConfidence: 91,
    avgWaitMins: 5,
  },
  {
    id: 'hs-3',
    name: 'Velachery Bypass Junction',
    category: 'junction',
    lat: 12.9774,
    lng: 80.2212,
    lit: true,
    legalStopping: true,
    waitingCount: 4,
    historicalConfidence: 89,
    avgWaitMins: 3,
  },
  {
    id: 'hs-4',
    name: 'Thiruvanmiyur MRTS',
    category: 'metro',
    lat: 12.9880,
    lng: 80.2546,
    lit: true,
    legalStopping: true,
    waitingCount: 1,
    historicalConfidence: 87,
    avgWaitMins: 6,
  },
  {
    id: 'hs-5',
    name: 'Madhya Kailash Junction',
    category: 'junction',
    lat: 13.0083,
    lng: 80.2442,
    lit: true,
    legalStopping: true,
    waitingCount: 2,
    historicalConfidence: 92,
    avgWaitMins: 4,
  },
  {
    id: 'hs-6',
    name: 'Tidel Park Gate',
    category: 'junction',
    lat: 12.9893,
    lng: 80.2483,
    lit: true,
    legalStopping: true,
    waitingCount: 5,
    historicalConfidence: 96,
    avgWaitMins: 2,
  },
  {
    id: 'hs-7',
    name: 'Sholinganallur Signal',
    category: 'junction',
    lat: 12.9010,
    lng: 80.2279,
    lit: true,
    legalStopping: true,
    waitingCount: 3,
    historicalConfidence: 85,
    avgWaitMins: 5,
  },
  {
    id: 'hs-8',
    name: 'Koyambedu Bus Terminus',
    category: 'bus_terminus',
    lat: 13.0694,
    lng: 80.1948,
    lit: true,
    legalStopping: true,
    waitingCount: 2,
    historicalConfidence: 90,
    avgWaitMins: 7,
  },
  {
    id: 'hs-9',
    name: 'Vadapalani Metro',
    category: 'metro',
    lat: 13.0512,
    lng: 80.2115,
    lit: true,
    legalStopping: true,
    waitingCount: 2,
    historicalConfidence: 88,
    avgWaitMins: 4,
  },
  {
    id: 'hs-10',
    name: 'Tambaram Railway Station',
    category: 'junction',
    lat: 12.9279,
    lng: 80.1136,
    lit: true,
    legalStopping: true,
    waitingCount: 4,
    historicalConfidence: 93,
    avgWaitMins: 5,
  },
];

// Seeded 14 users with distinct tiers and profiles
export const SEED_USERS: UserProfile[] = [
  {
    id: 'user-anitha',
    name: 'Anitha Ramesh',
    phone: '+91 98401 12345',
    avatar: '/demo/avatars/anitha.svg',
    role: 'both',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 78,
    trustBreakdown: {
      safety: 28,
      reliability: 21,
      peerFeedback: 12,
      verificationLevel: 8,
      consistency: 6,
      rideCount: 3,
      totalScore: 78,
    },
    streak: 9,
    cleanRides: 28,
    badges: ['Always On Time', 'Verified Peer', 'Pod Pioneer'],
    homeZone: 'Velachery',
    workZone: 'IIT Madras Main Gate',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: false },
    trustedContacts: [
      { id: 'c-1', name: 'Ramesh (Father)', phone: '+91 98401 99991' },
      { id: 'c-2', name: 'Divya (Friend)', phone: '+91 98401 99992' },
    ],
    responderActive: false,
  },
  {
    id: 'user-karthik',
    name: 'Karthik Subramanian',
    phone: '+91 98402 23456',
    avatar: '/demo/avatars/karthik.svg',
    role: 'both',
    activeRole: 'rider',
    tier: 'Verified Guardian',
    trustScore: 88,
    trustBreakdown: {
      safety: 32,
      reliability: 23,
      peerFeedback: 14,
      verificationLevel: 10,
      consistency: 5,
      rideCount: 4,
      totalScore: 88,
    },
    streak: 14,
    cleanRides: 62,
    badges: ['Safe Driver', 'Guardian Anchor', 'Punctual Star'],
    homeZone: 'Velachery',
    workZone: 'Anna University (Guindy)',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [
      { id: 'c-3', name: 'Lakshmi (Spouse)', phone: '+91 98402 88881' },
    ],
    responderActive: true,
  },
  {
    id: 'user-meenakshi',
    name: 'Meenakshi Sundaram',
    phone: '+91 98403 34567',
    avatar: '/demo/avatars/meenakshi.svg',
    role: 'both',
    activeRole: 'rider',
    tier: 'Community Anchor',
    trustScore: 94,
    trustBreakdown: {
      safety: 34,
      reliability: 24,
      peerFeedback: 15,
      verificationLevel: 10,
      consistency: 7,
      rideCount: 4,
      totalScore: 94,
    },
    streak: 25,
    cleanRides: 112,
    badges: ['Community Anchor', 'Peer Moderator', 'Zero Cancellation'],
    homeZone: 'Adyar',
    workZone: 'Tidel Park Gate',
    genderPref: 'any',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [
      { id: 'c-4', name: 'Sundaram (Partner)', phone: '+91 98403 77771' },
    ],
    isModerator: true,
    responderActive: true,
  },
  {
    id: 'user-divya',
    name: 'Divya Lakshmi',
    phone: '+91 98404 45678',
    avatar: '/demo/avatars/divya.svg',
    role: 'both',
    activeRole: 'passenger',
    tier: 'Community Anchor',
    trustScore: 92,
    trustBreakdown: { safety: 33, reliability: 23, peerFeedback: 14, verificationLevel: 10, consistency: 8, rideCount: 4, totalScore: 92 },
    streak: 19,
    cleanRides: 95,
    badges: ['Community Anchor', 'Peer Moderator', 'Women Pod Founder'],
    homeZone: 'Besant Nagar',
    workZone: 'Tidel Park Gate',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [{ id: 'c-5', name: 'Shreya', phone: '+91 98404 66661' }],
    isModerator: true,
    responderActive: true,
  },
  {
    id: 'user-arjun',
    name: 'Arjun Venkatesh',
    phone: '+91 98405 56789',
    avatar: '/demo/avatars/arjun.svg',
    role: 'both',
    activeRole: 'rider',
    tier: 'Verified Guardian',
    trustScore: 84,
    trustBreakdown: { safety: 30, reliability: 22, peerFeedback: 13, verificationLevel: 10, consistency: 5, rideCount: 4, totalScore: 84 },
    streak: 11,
    cleanRides: 48,
    badges: ['Verified Guardian', 'Smooth Driver'],
    homeZone: 'Thiruvanmiyur',
    workZone: 'Siruseri SIPCOT',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [{ id: 'c-6', name: 'Venkatesh', phone: '+91 98405 55551' }],
    responderActive: true,
  },
  {
    id: 'user-harish',
    name: 'Harish Kumar',
    phone: '+91 98406 67890',
    avatar: '/demo/avatars/harish.svg',
    role: 'passenger',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 74,
    trustBreakdown: { safety: 26, reliability: 20, peerFeedback: 12, verificationLevel: 8, consistency: 5, rideCount: 3, totalScore: 74 },
    streak: 6,
    cleanRides: 22,
    badges: ['Punctual Passenger'],
    homeZone: 'Mylapore',
    workZone: 'Anna University (Guindy)',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Newcomer',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: false },
    trustedContacts: [{ id: 'c-7', name: 'Kumar', phone: '+91 98406 44441' }],
    responderActive: false,
  },
  {
    id: 'user-priya',
    name: 'Priya Dharshini',
    phone: '+91 98407 78901',
    avatar: '/demo/avatars/priya.svg',
    role: 'passenger',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 79,
    trustBreakdown: { safety: 29, reliability: 21, peerFeedback: 13, verificationLevel: 8, consistency: 5, rideCount: 3, totalScore: 79 },
    streak: 8,
    cleanRides: 29,
    badges: ['Eco Commuter', 'Women Pod Member'],
    homeZone: 'Velachery',
    workZone: 'Perungudi',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: false },
    trustedContacts: [{ id: 'c-8', name: 'Mani', phone: '+91 98407 33331' }],
    responderActive: false,
  },
  {
    id: 'user-vignesh',
    name: 'Vignesh Rajan',
    phone: '+91 98408 89012',
    avatar: '/demo/avatars/vignesh.svg',
    role: 'rider',
    activeRole: 'rider',
    tier: 'Trusted',
    trustScore: 76,
    trustBreakdown: { safety: 27, reliability: 21, peerFeedback: 12, verificationLevel: 8, consistency: 5, rideCount: 3, totalScore: 76 },
    streak: 5,
    cleanRides: 19,
    badges: ['Reliable Carpooler'],
    homeZone: 'Porur',
    workZone: 'Guindy',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Newcomer',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [{ id: 'c-9', name: 'Rajan', phone: '+91 98408 22221' }],
    responderActive: false,
  },
  {
    id: 'user-nandhini',
    name: 'Nandhini Balaji',
    phone: '+91 98409 90123',
    avatar: '/demo/avatars/nandhini.svg',
    role: 'both',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 77,
    trustBreakdown: { safety: 28, reliability: 20, peerFeedback: 12, verificationLevel: 8, consistency: 6, rideCount: 3, totalScore: 77 },
    streak: 7,
    cleanRides: 25,
    badges: ['Women Pod Member'],
    homeZone: 'Tambaram',
    workZone: 'Sholinganallur',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: false },
    trustedContacts: [{ id: 'c-10', name: 'Balaji', phone: '+91 98409 11111' }],
    responderActive: false,
  },
  {
    id: 'user-suresh',
    name: 'Suresh Babu',
    phone: '+91 98410 01234',
    avatar: '/demo/avatars/suresh.svg',
    role: 'passenger',
    activeRole: 'passenger',
    tier: 'Newcomer',
    trustScore: 45,
    trustBreakdown: { safety: 18, reliability: 12, peerFeedback: 7, verificationLevel: 4, consistency: 2, rideCount: 2, totalScore: 45 },
    streak: 2,
    cleanRides: 4,
    badges: ['New Commuter'],
    homeZone: 'Chromepet',
    workZone: 'Guindy',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Newcomer',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: false, govtId: false, selfieMatch: false },
    trustedContacts: [],
    responderActive: false,
  },
  {
    id: 'user-aishwarya',
    name: 'Aishwarya Krishnan',
    phone: '+91 98411 12345',
    avatar: '/demo/avatars/aishwarya.svg',
    role: 'both',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 81,
    trustBreakdown: { safety: 29, reliability: 22, peerFeedback: 13, verificationLevel: 8, consistency: 6, rideCount: 3, totalScore: 81 },
    streak: 10,
    cleanRides: 34,
    badges: ['Verified Guardian in Training'],
    homeZone: 'Adyar',
    workZone: 'Taramani',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [{ id: 'c-11', name: 'Krishnan', phone: '+91 98411 99991' }],
    responderActive: false,
  },
  {
    id: 'user-irfan',
    name: 'Mohammed Irfan',
    phone: '+91 98412 23456',
    avatar: '/demo/avatars/irfan.svg',
    role: 'rider',
    activeRole: 'rider',
    tier: 'Verified Guardian',
    trustScore: 86,
    trustBreakdown: { safety: 31, reliability: 23, peerFeedback: 13, verificationLevel: 10, consistency: 5, rideCount: 4, totalScore: 86 },
    streak: 13,
    cleanRides: 57,
    badges: ['Night Commuter Champion', 'Verified Guardian'],
    homeZone: 'Pallavaram',
    workZone: 'Perungudi',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: true },
    trustedContacts: [{ id: 'c-12', name: 'Irfan Sr', phone: '+91 98412 88881' }],
    responderActive: true,
  },
  {
    id: 'user-fathima',
    name: 'Fathima Beevi',
    phone: '+91 98413 34567',
    avatar: '/demo/avatars/fathima.svg',
    role: 'passenger',
    activeRole: 'passenger',
    tier: 'Trusted',
    trustScore: 75,
    trustBreakdown: { safety: 27, reliability: 20, peerFeedback: 12, verificationLevel: 8, consistency: 5, rideCount: 3, totalScore: 75 },
    streak: 6,
    cleanRides: 20,
    badges: ['Clean Commute Supporter'],
    homeZone: 'T. Nagar',
    workZone: 'Loyola College',
    genderPref: 'women-only',
    gender: 'female',
    safeRoutePref: true,
    minTierFilter: 'Trusted',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: true, selfieMatch: false },
    trustedContacts: [{ id: 'c-13', name: 'Rahim', phone: '+91 98413 77771' }],
    responderActive: false,
  },
  {
    id: 'user-joseph',
    name: 'Joseph Anthony',
    phone: '+91 98414 45678',
    avatar: '/demo/avatars/joseph.svg',
    role: 'passenger',
    activeRole: 'passenger',
    tier: 'Newcomer',
    trustScore: 48,
    trustBreakdown: { safety: 19, reliability: 13, peerFeedback: 8, verificationLevel: 4, consistency: 2, rideCount: 2, totalScore: 48 },
    streak: 1,
    cleanRides: 3,
    badges: ['New Joiner'],
    homeZone: 'Anna Nagar',
    workZone: 'Loyola College',
    genderPref: 'any',
    gender: 'male',
    safeRoutePref: false,
    minTierFilter: 'Newcomer',
    verificationSteps: { phoneOtp: true, collegeOrEmployerId: true, govtId: false, selfieMatch: false },
    trustedContacts: [],
    responderActive: false,
  },
];

// Seeded Vehicles (cars only for v1, illustratively assigned to riders)
export const SEED_VEHICLES: Vehicle[] = [
  {
    id: 'veh-karthik',
    ownerId: 'user-karthik',
    makeModel: 'Honda City',
    type: 'sedan',
    plate: 'TN 09 AB 4821',
    seats: 3,
    fuelType: 'petrol',
    mileageKmPerLitre: 15,
    licenseDocUrl: '/demo/docs/driver_license_sample.svg',
    approved: true,
  },
  {
    id: 'veh-meenakshi',
    ownerId: 'user-meenakshi',
    makeModel: 'Hyundai i20',
    type: 'hatchback',
    plate: 'TN 01 GH 6754',
    seats: 3,
    fuelType: 'petrol',
    mileageKmPerLitre: 16,
    licenseDocUrl: '/demo/docs/driver_license_sample.svg',
    approved: true,
  },
  {
    id: 'veh-arjun',
    ownerId: 'user-arjun',
    makeModel: 'Tata Nexon EV',
    type: 'suv',
    plate: 'TN 07 CD 2341',
    seats: 3,
    fuelType: 'ev',
    mileageKmPerLitre: 22,
    licenseDocUrl: '/demo/docs/driver_license_sample.svg',
    approved: true,
  },
  {
    id: 'veh-irfan',
    ownerId: 'user-irfan',
    makeModel: 'Maruti Dzire',
    type: 'sedan',
    plate: 'TN 11 EF 9081',
    seats: 4,
    fuelType: 'cng',
    mileageKmPerLitre: 24,
    licenseDocUrl: '/demo/docs/driver_license_sample.svg',
    approved: true,
  },
];

// Seeded Ghost Commute predictions
export const SEED_GHOST_PREDICTIONS: GhostPrediction[] = [
  {
    id: 'pred-anitha-1',
    userId: 'user-anitha',
    targetRole: 'passenger',
    date: 'Tomorrow',
    time: '08:10',
    origin: 'Velachery Bypass Junction',
    destination: 'IIT Madras Main Gate',
    corridor: 'Velachery → Guindy → IIT Madras',
    confidence: 86,
    ridersCount: 3,
    estimatedCostShare: 28,
    status: 'proposed',
  },
  {
    id: 'pred-karthik-1',
    userId: 'user-karthik',
    targetRole: 'rider',
    date: 'Tomorrow',
    time: '08:10',
    origin: 'Velachery Bypass Junction',
    destination: 'Anna University (Guindy)',
    corridor: 'Velachery → Guindy → IIT Madras',
    confidence: 82,
    seatsOffered: 3,
    estimatedCostShare: 84, // of total ~96
    status: 'proposed',
  },
  {
    id: 'pred-divya-1',
    userId: 'user-divya',
    targetRole: 'passenger',
    date: 'Tomorrow',
    time: '08:45',
    origin: 'Adyar Signal',
    destination: 'Tidel Park Gate',
    corridor: 'Adyar → Perungudi → Tidel Park',
    confidence: 91,
    ridersCount: 2,
    estimatedCostShare: 24,
    status: 'proposed',
  },
  {
    id: 'pred-arjun-1',
    userId: 'user-arjun',
    targetRole: 'rider',
    date: 'Tomorrow',
    time: '09:00',
    origin: 'Thiruvanmiyur MRTS',
    destination: 'Siruseri SIPCOT',
    corridor: 'Thiruvanmiyur → Perungudi → Sholinganallur → Siruseri',
    confidence: 78,
    seatsOffered: 3,
    estimatedCostShare: 75,
    status: 'proposed',
  },
  {
    id: 'pred-harish-1',
    userId: 'user-harish',
    targetRole: 'passenger',
    date: 'Tomorrow',
    time: '08:30',
    origin: 'Madhya Kailash Junction',
    destination: 'Anna University (Guindy)',
    corridor: 'Adyar → Guindy',
    confidence: 72,
    ridersCount: 2,
    estimatedCostShare: 22,
    status: 'proposed',
  },
  {
    id: 'pred-nandhini-1',
    userId: 'user-nandhini',
    targetRole: 'passenger',
    date: 'Tomorrow',
    time: '08:15',
    origin: 'Tambaram Railway Station',
    destination: 'Sholinganallur Signal',
    corridor: 'Tambaram → Guindy → OMR',
    confidence: 85,
    ridersCount: 3,
    estimatedCostShare: 42,
    status: 'proposed',
  },
];

// Seeded Pods
export const SEED_PODS: Pod[] = [
  {
    id: 'pod-velachery-it',
    name: 'Velachery Tech Corridor Pod',
    corridor: 'Velachery → Guindy → IIT Madras',
    members: [
      { userId: 'user-karthik', name: 'Karthik S.', avatar: '/demo/avatars/karthik.svg', tier: 'Verified Guardian', role: 'driver', drivingDays: ['Mon', 'Wed'] },
      { userId: 'user-anitha', name: 'Anitha R.', avatar: '/demo/avatars/anitha.svg', tier: 'Trusted', role: 'passenger', drivingDays: [] },
      { userId: 'user-harish', name: 'Harish K.', avatar: '/demo/avatars/harish.svg', tier: 'Trusted', role: 'passenger', drivingDays: [] },
      { userId: 'user-priya', name: 'Priya D.', avatar: '/demo/avatars/priya.svg', tier: 'Trusted', role: 'driver', drivingDays: ['Tue', 'Thu', 'Fri'] },
    ],
    todayDriverId: 'user-karthik',
    reputation: 94,
    totalMoneySaved: 3840,
    totalCo2SavedKg: 54.2,
    streakCount: 16,
    isWomenOnly: false,
    standbyCandidates: [
      { userId: 'user-vignesh', name: 'Vignesh Rajan', tier: 'Trusted' },
    ],
  },
  {
    id: 'pod-women-omr',
    name: 'OMR Women Commute Circle',
    corridor: 'Adyar → Perungudi → Tidel Park',
    members: [
      { userId: 'user-divya', name: 'Divya L.', avatar: '/demo/avatars/divya.svg', tier: 'Community Anchor', role: 'driver', drivingDays: ['Mon', 'Tue', 'Thu'] },
      { userId: 'user-meenakshi', name: 'Meenakshi S.', avatar: '/demo/avatars/meenakshi.svg', tier: 'Community Anchor', role: 'driver', drivingDays: ['Wed', 'Fri'] },
      { userId: 'user-aishwarya', name: 'Aishwarya K.', avatar: '/demo/avatars/aishwarya.svg', tier: 'Trusted', role: 'passenger', drivingDays: [] },
      { userId: 'user-fathima', name: 'Fathima B.', avatar: '/demo/avatars/fathima.svg', tier: 'Trusted', role: 'passenger', drivingDays: [] },
    ],
    todayDriverId: 'user-divya',
    reputation: 98,
    totalMoneySaved: 5120,
    totalCo2SavedKg: 78.5,
    streakCount: 22,
    isWomenOnly: true,
    standbyCandidates: [
      { userId: 'user-nandhini', name: 'Nandhini Balaji', tier: 'Trusted' },
    ],
  },
];

// Live SafeTrail demo ride ready out-of-the-box (Karthik driving, Anitha passenger)
export const SEED_LIVE_RIDE: Ride = {
  id: 'ride-54266',
  riderId: 'user-karthik',
  riderName: 'Karthik Subramanian',
  riderAvatar: '/demo/avatars/karthik.svg',
  riderTier: 'Verified Guardian',
  vehicle: SEED_VEHICLES[0],
  originName: 'Velachery Bypass Junction',
  originLat: 12.9774,
  originLng: 80.2212,
  destName: 'IIT Madras Main Gate',
  destLat: 12.9915,
  destLng: 80.2337,
  departureTime: '08:15',
  corridor: 'Velachery → Guindy → IIT Madras',
  status: 'IN_TRANSIT',
  participants: [
    {
      userId: 'user-anitha',
      name: 'Anitha Ramesh',
      avatar: '/demo/avatars/anitha.svg',
      tier: 'Trusted',
      pickupHotspotId: 'hs-3',
      pickupName: 'Velachery Bypass Junction',
      pickupLat: 12.9774,
      pickupLng: 80.2212,
      exactPickupPoint: { lat: 12.9778, lng: 80.2215, address: 'Near Velachery Bypass Bus Shelter, 100ft Road' },
      dropName: 'IIT Madras Main Gate',
      dropLat: 12.9915,
      dropLng: 80.2337,
      status: 'onboard',
      fareShare: 28,
      fareReason: 'Direct corridor share + 0.4 km detour offset',
    },
  ],
  rideCode: '4821',
  costCappedTotal: 96,
  actualCost: 92,
  costRecovered: 28,
  currentRiderPosition: { lat: 12.9810, lng: 80.2245, heading: 45 },
  routePolyline: [
    [12.9774, 80.2212],
    [12.9805, 80.2238],
    [12.9840, 80.2270],
    [12.9875, 80.2305],
    [12.9915, 80.2337],
  ],
};

// Seeded Wallets and double-entry Ledgers
export const SEED_WALLETS: Record<string, Wallet> = {
  'user-anitha': {
    userId: 'user-anitha',
    balance: 412,
    ledger: [
      { id: 'tx-1', timestamp: '2026-09-28 17:30', description: 'UPI Top-up', amount: 500, type: 'topup' },
      { id: 'tx-2', timestamp: '2026-09-28 09:12', description: 'Ride to IIT Madras share', amount: -28, type: 'fare_debit', rideId: 'ride-54201' },
      { id: 'tx-3', timestamp: '2026-09-27 18:05', description: 'Ride from Campus share', amount: -30, type: 'fare_debit', rideId: 'ride-54190' },
      { id: 'tx-4', timestamp: '2026-09-26 08:45', description: 'Relay pass metro leg', amount: -15, type: 'fare_debit' },
      { id: 'tx-5', timestamp: '2026-09-25 19:10', description: 'Ride share refund (cancellation)', amount: 28, type: 'refund' },
    ],
  },
  'user-karthik': {
    userId: 'user-karthik',
    balance: 640,
    ledger: [
      { id: 'tx-6', timestamp: '2026-09-28 09:15', description: 'Fuel cost recovery · Velachery loop', amount: 84, type: 'cost_recovery_credit', rideId: 'ride-54201' },
      { id: 'tx-7', timestamp: '2026-09-28 09:15', description: 'Platform maintenance fee (5%)', amount: -4, type: 'fee_debit' },
      { id: 'tx-8', timestamp: '2026-09-27 18:10', description: 'Fuel cost recovery · Guindy drop', amount: 76, type: 'cost_recovery_credit', rideId: 'ride-54190' },
      { id: 'tx-9', timestamp: '2026-09-26 09:10', description: 'Fuel cost recovery · IIT corridor', amount: 84, type: 'cost_recovery_credit' },
      { id: 'tx-10', timestamp: '2026-09-25 18:30', description: 'Fuel cost recovery · Evening return', amount: 62, type: 'cost_recovery_credit' },
    ],
  },
};

// Hand-built Chennai Transit Table (stops, coordinates, timings, fares)
// COMMENT: DEMO DATA, not real timetables. MTC bus routes and Chennai Metro station data.
export const SEED_TRANSIT_ROUTES = [
  {
    routeId: 'MTC-570',
    name: 'MTC Route 570 (Koyambedu ⇄ Siruseri SIPCOT)',
    type: 'bus' as const,
    frequencyMins: 10,
    fareRs: 18,
    stops: [
      { name: 'Guindy Metro', lat: 13.0092, lng: 80.2131 },
      { name: 'Velachery Checkpost', lat: 12.9815, lng: 80.2180 },
      { name: 'Tidel Park Gate', lat: 12.9893, lng: 80.2483 },
      { name: 'Perungudi Toll', lat: 12.9654, lng: 80.2461 },
      { name: 'Sholinganallur Signal', lat: 12.9010, lng: 80.2279 },
      { name: 'Siruseri SIPCOT', lat: 12.8300, lng: 80.2180 },
    ],
  },
  {
    routeId: 'MTC-19B',
    name: 'MTC Route 19B (T. Nagar ⇄ Kelambakkam)',
    type: 'bus' as const,
    frequencyMins: 12,
    fareRs: 15,
    stops: [
      { name: 'Madhya Kailash', lat: 13.0083, lng: 80.2442 },
      { name: 'Tidel Park Gate', lat: 12.9893, lng: 80.2483 },
      { name: 'Thiruvanmiyur', lat: 12.9830, lng: 80.2594 },
      { name: 'Perungudi', lat: 12.9654, lng: 80.2461 },
      { name: 'Sholinganallur', lat: 12.9010, lng: 80.2279 },
    ],
  },
  {
    routeId: 'CMRL-BLUE',
    name: 'Chennai Metro Blue Line (Wimco Nagar ⇄ Airport)',
    type: 'metro' as const,
    frequencyMins: 6,
    fareRs: 20,
    stops: [
      { name: 'Vadapalani Metro', lat: 13.0512, lng: 80.2115 },
      { name: 'Guindy Metro', lat: 13.0092, lng: 80.2131 },
      { name: 'Meenambakkam', lat: 12.9877, lng: 80.1764 },
      { name: 'Chennai Airport', lat: 12.9798, lng: 80.1650 },
    ],
  },
];

// Moderator Cases (1 flagged ride and 1 dispute)
export const SEED_MODERATOR_CASES: ModeratorCase[] = [
  {
    id: 'case-901',
    type: 'flagged_ride',
    status: 'pending',
    anonymisedUserA: 'Passenger #8812',
    anonymisedUserB: 'Rider #4490',
    reason: 'Unexplained 4 km route deviation',
    details: 'Ride on Velachery corridor took outer bypass without prior mutual agreement in chat.',
    submittedAt: '2026-09-28 19:42',
    conflictPodId: 'pod-velachery-it', // Demonstrates conflict-of-interest check for Karthik/Anitha
  },
  {
    id: 'case-902',
    type: 'dispute',
    status: 'pending',
    anonymisedUserA: 'Passenger #3319',
    anonymisedUserB: 'Rider #1204',
    reason: 'Incorrect toll addition in fare',
    details: 'Passenger claims no toll gate was crossed between Guindy and Anna University campus.',
    submittedAt: '2026-09-29 07:15',
  },
  {
    id: 'case-903',
    type: 'hotspot_nomination',
    status: 'pending',
    anonymisedUserA: 'Commuter #5521',
    reason: 'Nominate IIT Madras Main Gate (Bus Bay)',
    details: '5 routes overlap; well-lit, CCTV covered, legal stopping bay outside campus gate.',
    submittedAt: '2026-09-29 08:30',
  },
];

export const SEED_AUDIT_LOG: AuditLogEntry[] = [
  {
    id: 'audit-1',
    moderatorId: 'user-meenakshi',
    moderatorName: 'Meenakshi Sundaram',
    caseId: 'case-898',
    action: 'Approved hotspot nomination for Guindy Metro Bay 2',
    timestamp: '2026-09-27 11:20',
    notes: 'Verified site photos and legal stopping clearance.',
  },
  {
    id: 'audit-2',
    moderatorId: 'user-divya',
    moderatorName: 'Divya Lakshmi',
    caseId: 'case-899',
    action: 'Dismissed no-show dispute with passenger warning',
    timestamp: '2026-09-27 16:45',
    notes: 'GPS telemetry confirmed rider waited 7 minutes at designated hotspot.',
  },
];
